//! `[ports]` + `[compose]` — slot allocation, the `.worktree.env` wire format,
//! and the one piece of docker argv the tool assembles (proposal §3, §5, §6).
//!
//! Three layers, same discipline as `materialize.rs`:
//!
//! ```text
//! select_slot / render_env / compose_project_name   PURE — the whole test surface
//! scan / port_free / read_env                       the only filesystem+socket READS
//! provision                                         the only filesystem WRITE
//! ```
//!
//! ⚠ **The slot is DERIVED, never stored in `.worktrees.places.json`** (§6). The
//! store's contract is sticky user intent that survives the worktree being gone,
//! and `remove_one` never calls `store::edit` — so a stored slot would leak on
//! every `rm` and turn `max_slots` into a silent exhaustion bug months later.
//! Deriving it from each place's own `.worktree.env` means there is **no release
//! step at all**: `rm` deletes the directory, the env file goes with it, and the
//! next scan sees the hole.
//!
//! ⚠ **`.worktree.env` is a public wire format, not an internal artifact** (§3).
//! Six consumers read it and at least one does `set -a; . .worktree.env`, so
//! every emitted line is sourced AS SHELL. Two things follow, and both are
//! load-bearing:
//!
//! - `WORKTREE_SLOT` is emitted even though the tool could re-derive it. A
//!   consumer keys a behavior off its mere presence; dropping it as "internal
//!   state" reintroduces a bug that repo already debugged once.
//! - The variable NAMES are the contract, and a name that is not a valid POSIX
//!   shell name emits a line that *executes* instead of assigning. `lint_ports`
//!   (`projcfg.rs`) already rejects those at parse time — [`render_env`] asserts
//!   it again rather than trusting it silently, because the two are separated by
//!   a module boundary and a future parser change must not be able to open this
//!   quietly.
//!
//! ⚠ **A hand-edited `.worktree.env` wins.** Allocation never rewrites an
//! existing `WORKTREE_SLOT` without `--reallocate`: it is the file the running
//! stack sources, and the tool disagreeing with it would be the tool lying. The
//! same holds for `COMPOSE_PROJECT_NAME` — it names the containers that are
//! actually up, so a `[compose] project` template that changed since does not
//! move it; `doctor` reports the drift (`Code::ComposeDrift`) instead.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fs;
use std::io;
use std::net::{Ipv4Addr, TcpListener};
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::config::sanitize_prefix;
use crate::projcfg::{Compose, Ports, ProjectConfig};

/// Tool-owned, like `.worktrees.places.json`. Deliberately NOT configurable:
/// allocation works by scanning siblings for this file, and a repo that renamed
/// it after worktrees existed would make the old places invisible to the scan
/// and double-allocate their slots (§3).
pub const ENV_FILE: &str = ".worktree.env";

/// `mkdir(2)`-based cross-process lock, held only for the scan + the write.
pub const LOCK_DIR: &str = ".worktrees.slots.lock";

/// §6: ~3s of 15ms rounds before the lock is declared un-acquirable.
const LOCK_ROUNDS: u32 = 200;
const LOCK_BACKOFF_MS: u64 = 15;
/// How many consecutive rounds a lock with no readable PID must be seen before
/// it counts as stale. `create_dir` and the pid write are not one atomic step,
/// so a single miss may just be a racing acquirer mid-handshake.
const LOCK_PIDLESS_ROUNDS: u32 = 3;

const HEADER: &str = "\
# .worktree.env — generated by `worktrees provision`, one per worktree.
# Sourced as shell (`set -a; . .worktree.env`), so every line is KEY=value.
# WORKTREE_SLOT is yours: the tool never rewrites it without --reallocate.
";

// ── the wire format ──────────────────────────────────────────────────────────

/// What a `.worktree.env` says. Only the two keys the tool itself consumes are
/// extracted; everything else is the repo's business.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct EnvFile {
    pub slot: Option<u32>,
    pub compose_project: Option<String>,
    /// Every NAME the file assigns, whatever its value. Not "everything else
    /// parsed" — just the key set, and only because `doctor` has to answer "does
    /// this file declare every port `[ports].base` names?". A file written before
    /// a port joined the map has a slot, is unique, and still leaves that service
    /// bound on main's port (§6); without the key set that is invisible.
    pub keys: BTreeSet<String>,
}

/// Parse an EXISTING `.worktree.env` tolerantly. PURE.
///
/// Deliberately lenient, unlike `.worktrees.toml`: §12 says the migration is not
/// a clean slate — existing places carry slots written by a bash script, and
/// `provision`'s "already has a slot → no-op" path has to be able to ADOPT them.
/// So `export `, quotes, comments, CRLF and trailing junk are all tolerated, and
/// the LAST parseable assignment wins (which is what the shell itself would do).
pub fn parse_env(text: &str) -> EnvFile {
    let mut out = EnvFile::default();
    for line in text.lines() {
        let l = line.trim();
        // `export` is a WORD, so any blank may follow it — a tab is what a
        // heredoc-indented script writes, and it must not read as `export\tFOO`
        // being a key.
        let l = l
            .strip_prefix("export")
            .filter(|r| r.starts_with(' ') || r.starts_with('\t'))
            .map(str::trim_start)
            .unwrap_or(l);
        if l.is_empty() || l.starts_with('#') {
            continue;
        }
        let Some((key, val)) = l.split_once('=') else { continue };
        let val = shell_value(val.trim());
        out.keys.insert(key.trim().to_string());
        match key.trim() {
            "WORKTREE_SLOT" => {
                if let Ok(n) = val.parse::<u32>() {
                    out.slot = Some(n);
                }
            }
            "COMPOSE_PROJECT_NAME" if !val.is_empty() => out.compose_project = Some(val),
            _ => {}
        }
    }
    out
}

/// `"x"` / `'x'` → `x`; an unquoted value ends at the first whitespace, because
/// `FOO=bar # note` assigns `bar` in every POSIX shell.
///
/// A quoted value ends at its CLOSING quote, not at end of line: `FOO="bar" #
/// note` assigns `bar` too, and keeping the quotes here would hand `"bar"` to
/// something that then compares it against a name. An unterminated quote is junk;
/// take it as far as it goes rather than invent a value.
fn shell_value(v: &str) -> String {
    for q in ['"', '\''] {
        if let Some(rest) = v.strip_prefix(q) {
            return match rest.split_once(q) {
                Some((inner, _)) => inner.to_string(),
                None => rest.to_string(),
            };
        }
    }
    v.split_whitespace().next().unwrap_or("").to_string()
}

/// `(raw text, parsed)` for `<wt>/.worktree.env`, or `None` when it is absent.
pub fn read_env(wt: &Path) -> Option<(String, EnvFile)> {
    let text = fs::read_to_string(wt.join(ENV_FILE)).ok()?;
    let parsed = parse_env(&text);
    Some((text, parsed))
}

/// The exact bytes of the file we own (§3's emitted content). PURE.
///
/// `Err` is unreachable through `projcfg::parse` — every base key was validated
/// shell-safe by `lint_ports`, and the compose name has been through
/// `sanitize_prefix`. It is a `Result` rather than a `debug_assert!` anyway: the
/// failure mode this guards is "emit a line that EXECUTES when sourced", and a
/// check that compiles out in release is not a check.
pub fn render_env(slot: u32, ports: &Ports, compose_project: Option<&str>) -> Result<String, String> {
    let mut s = String::with_capacity(HEADER.len() + 32 * (ports.base.len() + 2));
    s.push_str(HEADER);
    s.push_str(&format!("WORKTREE_SLOT={slot}\n"));
    if let Some(p) = compose_project {
        if !is_shell_word(p) {
            return Err(format!(
                "compose project name `{p}` is not shell-safe — refusing to write {ENV_FILE}"
            ));
        }
        s.push_str(&format!("COMPOSE_PROJECT_NAME={p}\n"));
    }
    // BTreeMap ⇒ sorted by base key, so the file is byte-stable across runs and
    // a diff only ever shows a real change.
    for (name, base) in &ports.base {
        if !is_shell_name(name) {
            return Err(format!(
                "[ports] base key `{name}` is not a shell-safe name — refusing to write {ENV_FILE}"
            ));
        }
        let port = port_for(*base, ports.stride, slot)?;
        s.push_str(&format!("{name}_PORT={port}\n"));
    }
    Ok(s)
}

/// `[A-Za-z_][A-Za-z0-9_]*` — the same rule `lint_ports` applies at parse time.
fn is_shell_name(s: &str) -> bool {
    let mut cs = s.chars();
    match cs.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => cs.all(|c| c.is_ascii_alphanumeric() || c == '_'),
        _ => false,
    }
}

/// A value that needs no quoting: exactly `sanitize_prefix`'s output alphabet.
fn is_shell_word(s: &str) -> bool {
    !s.is_empty()
        && s.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-')
}

/// `base + stride * k`, refused past the port ceiling. `lint_ports` already
/// proved this fits for every `k <= max_slots`; this is the arithmetic belt.
pub fn port_for(base: u32, stride: u32, k: u32) -> Result<u32, String> {
    let p = stride
        .checked_mul(k)
        .and_then(|off| base.checked_add(off))
        .filter(|p| *p <= 65535)
        .ok_or_else(|| format!("port {base} + {stride}×{k} is past the 65535 ceiling"))?;
    Ok(p)
}

/// Every `<NAME>_PORT` this slot occupies, sorted by name.
pub fn slot_ports(ports: &Ports, k: u32) -> Result<Vec<(String, u32)>, String> {
    ports
        .base
        .iter()
        .map(|(n, b)| port_for(*b, ports.stride, k).map(|p| (format!("{n}_PORT"), p)))
        .collect()
}

// ── slot selection — PURE ────────────────────────────────────────────────────

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SlotError {
    /// §6: name how many slots are declared and how many are port-busy, so the
    /// remedy ("remove a worktree" vs "stop whatever squats 3300") is visible.
    Exhausted { max_slots: u32, declared: usize, busy: usize },
}

impl fmt::Display for SlotError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SlotError::Exhausted { max_slots, declared, busy } => write!(
                f,
                "no free slot in 1..={max_slots} ({declared} declared by other places, \
                 {busy} port-busy)"
            ),
        }
    }
}

/// The lowest free `k` in `1..=max_slots` (§6 step 4). PURE: a function of the
/// declared set, `max_slots`, and the probe's answers — so every rule here is
/// testable without binding a single socket.
///
/// `declared` must ALREADY count a conflicted slot as used (see
/// [`SlotScan::used_excluding`]) so that conflicts never compound.
pub fn select_slot(
    declared: &BTreeSet<u32>,
    max_slots: u32,
    mut ports_free: impl FnMut(u32) -> bool,
) -> Result<u32, SlotError> {
    let mut busy = 0usize;
    for k in 1..=max_slots {
        if declared.contains(&k) {
            continue;
        }
        // The probe is only the tiebreaker for "some unrelated process squats
        // 3300" — the declared set, not the probe, is what makes an assignment
        // stable (§6).
        if !ports_free(k) {
            busy += 1;
            continue;
        }
        return Ok(k);
    }
    Err(SlotError::Exhausted {
        max_slots,
        declared: declared.iter().filter(|k| **k >= 1 && **k <= max_slots).count(),
        busy,
    })
}

// ── the probe ────────────────────────────────────────────────────────────────

/// Free ⇔ bindable on BOTH `127.0.0.1` and `0.0.0.0`, closed immediately.
///
/// §6: `TcpListener::bind`, never `lsof` — no external binary to depend on,
/// ~100× faster, identical on macOS and Linux, and no false negative on
/// docker-proxy. std sets `SO_REUSEADDR`, so a `TIME_WAIT` socket may bind;
/// that is accepted, because the probe is a tiebreaker and not the source of
/// truth.
pub fn port_free(port: u32) -> bool {
    let Ok(port) = u16::try_from(port) else { return false };
    [Ipv4Addr::LOCALHOST, Ipv4Addr::UNSPECIFIED]
        .into_iter()
        .all(|a| TcpListener::bind((a, port)).is_ok())
}

/// Are every port of slot `k` bindable? A malformed port (past the ceiling)
/// counts as NOT free, which pushes selection past the slot rather than
/// emitting something impossible.
pub fn slot_ports_free(ports: &Ports, k: u32) -> bool {
    match slot_ports(ports, k) {
        Ok(list) => list.iter().all(|(_, p)| port_free(*p)),
        Err(_) => false,
    }
}

// ── the scan (impure, runs INSIDE the lock) ──────────────────────────────────

/// Who claims which slot, per §6 step 2. `main_root` implicitly holds slot 0.
#[derive(Clone, Debug, Default)]
pub struct SlotScan {
    /// slot → every dir claiming it, in scan order. More than one ⇒ CONFLICT.
    pub claims: BTreeMap<u32, Vec<PathBuf>>,
}

impl SlotScan {
    pub fn slot_of(&self, dir: &Path) -> Option<u32> {
        let dir = real(dir);
        self.claims.iter().find(|(_, v)| v.iter().any(|d| *d == dir)).map(|(k, _)| *k)
    }

    /// Another place holding `slot`, if any — the conflict `provision` refuses on.
    pub fn other_claimant(&self, slot: u32, dir: &Path) -> Option<&Path> {
        let dir = real(dir);
        self.claims.get(&slot)?.iter().find(|d| **d != dir).map(PathBuf::as_path)
    }

    /// Slots claimed by anyone OTHER than `dir`. A conflicted slot appears here
    /// exactly like a cleanly-held one — that is what makes "a conflicted k
    /// counts as USED" true, so conflicts never compound.
    pub fn used_excluding(&self, dir: &Path) -> BTreeSet<u32> {
        let dir = real(dir);
        self.claims
            .iter()
            .filter(|(_, v)| v.iter().any(|d| *d != dir))
            .map(|(k, _)| *k)
            .collect()
    }

    /// Every slot claimed by two or more places.
    pub fn conflicts(&self) -> Vec<(u32, &[PathBuf])> {
        self.claims
            .iter()
            .filter(|(_, v)| v.len() > 1)
            .map(|(k, v)| (*k, v.as_slice()))
            .collect()
    }
}

/// Read every sibling place's `.worktree.env`. Unregistered (stale) dirs ARE
/// scanned: a stale dir can still have a running stack on its ports, and
/// double-allocating over it is exactly the destructive case §1.1 is about.
pub fn scan(main_root: &Path, wt_root: &Path) -> SlotScan {
    let mut out = SlotScan::default();
    // The main checkout implicitly holds slot 0, so nothing can ever be handed
    // the ports the developer's primary stack already uses.
    out.claims.entry(0).or_default().push(real(main_root));
    let mut dirs: Vec<PathBuf> = match fs::read_dir(wt_root) {
        Ok(rd) => rd.filter_map(|e| e.ok()).map(|e| e.path()).filter(|p| p.is_dir()).collect(),
        Err(_) => Vec::new(),
    };
    dirs.sort();
    for d in dirs {
        if let Some((_, env)) = read_env(&d) {
            if let Some(k) = env.slot {
                out.claims.entry(k).or_default().push(real(&d));
            }
        }
    }
    out
}

/// Canonical form, falling back to the literal path. Places are named four
/// different ways across ops (`format!`, git's porcelain, `read_dir`); comparing
/// resolved paths is what keeps "is this the same place?" from depending on
/// which one the caller happened to hold.
fn real(p: &Path) -> PathBuf {
    fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf())
}

// ── the lock ─────────────────────────────────────────────────────────────────

/// `mkdir(2)` O_EXCL at `<main_root>/.worktrees.slots.lock`, PID inside.
///
/// ⚠ **PID-liveness, not wall-clock.** `store.rs:104-113` declares its lock
/// stale after 15s of mtime age, which contradicts `DESIGN.md:205` and
/// false-positives across a laptop sleep — two provisions would then scan
/// concurrently and hand out the same slot. That heuristic is deliberately NOT
/// reused here, and `store.rs` is deliberately NOT changed by this slice: its
/// lock guards a field-merge that is idempotent under a double write, so the
/// contradiction is a latent wart there and a correctness bug here. Fixing it
/// there changes behavior the places-store tests pin, and belongs in its own
/// change.
pub struct SlotLock {
    dir: PathBuf,
    /// Our own stamp, re-checked at [`Drop`]. A lock is not a directory that
    /// exists, it is a directory whose `pid` is OURS.
    pid: i32,
}

impl SlotLock {
    pub fn acquire(main_root: &Path) -> Result<SlotLock, String> {
        let dir = main_root.join(LOCK_DIR);
        let pid_file = dir.join("pid");
        let me = std::process::id() as i32;
        let mut pidless = 0u32;
        let mut holder: Option<i32> = None;
        for _ in 0..LOCK_ROUNDS {
            match fs::create_dir(&dir) {
                Ok(()) => {
                    // `create_dir` and the stamp are two syscalls, and the gap
                    // between them is exactly the window a waiter evicts on
                    // (LOCK_PIDLESS_ROUNDS below). So the stamp is NOT
                    // fire-and-forget: if it did not land — the write failed, or
                    // someone evicted us mid-handshake — we do not hold this
                    // lock, and returning one anyway puts two scans on the same
                    // slot map (§1.1). Retry instead; the pidless path reclaims
                    // whatever we left behind, and it waits before doing so
                    // precisely so it cannot rip a lock out of a racing acquirer.
                    if stamp(&pid_file, me) {
                        return Ok(SlotLock { dir, pid: me });
                    }
                    pidless = 0;
                    std::thread::sleep(std::time::Duration::from_millis(LOCK_BACKOFF_MS));
                }
                Err(e) if e.kind() == io::ErrorKind::AlreadyExists => {
                    match read_pid(&pid_file) {
                        Some(pid) if pid_alive(pid) => {
                            holder = Some(pid);
                            pidless = 0;
                            std::thread::sleep(std::time::Duration::from_millis(LOCK_BACKOFF_MS));
                        }
                        Some(_) => {
                            // ESRCH: the holder died mid-scan. Reclaim and retry.
                            let _ = fs::remove_file(&pid_file);
                            let _ = fs::remove_dir(&dir);
                            pidless = 0;
                        }
                        None => {
                            // No readable PID. That is EITHER a crash between
                            // `mkdir` and the pid write, OR a racing acquirer
                            // still inside that window — so wait it out before
                            // reclaiming, or two processes both "reclaim" a lock
                            // the other is legitimately holding.
                            pidless += 1;
                            if pidless >= LOCK_PIDLESS_ROUNDS {
                                let _ = fs::remove_dir(&dir);
                                pidless = 0;
                            }
                            std::thread::sleep(std::time::Duration::from_millis(LOCK_BACKOFF_MS));
                        }
                    }
                }
                Err(e) => return Err(format!("cannot create {}: {e}", dir.display())),
            }
        }
        Err(match holder {
            Some(pid) => format!(
                "slot lock {} is held by pid {pid} — another `worktrees provision` is running \
                 (if it is not, remove that directory)",
                dir.display()
            ),
            None => format!("could not acquire the slot lock {}", dir.display()),
        })
    }
}

impl Drop for SlotLock {
    fn drop(&mut self) {
        let pid_file = self.dir.join("pid");
        // Ownership-checked, not unconditional: if the stamp is no longer ours we
        // were evicted, the directory belongs to whoever holds it NOW, and
        // removing it would drop a lock in the middle of someone else's scan —
        // letting a third process in and handing out a slot twice (§1.1).
        if read_pid(&pid_file) != Some(self.pid) {
            return;
        }
        let _ = fs::remove_file(&pid_file);
        // `remove_dir`, never `remove_dir_all`: this must not become a recursive
        // delete rooted at a path a config could influence.
        let _ = fs::remove_dir(&self.dir);
    }
}

/// Write our pid and read it back. `false` = the stamp did not take (the write
/// failed, or a waiter evicted us inside the `mkdir`→write window), which is
/// indistinguishable from never having held the lock and is treated as such.
fn stamp(pid_file: &Path, me: i32) -> bool {
    fs::write(pid_file, format!("{me}\n")).is_ok() && read_pid(pid_file) == Some(me)
}

fn read_pid(pid_file: &Path) -> Option<i32> {
    fs::read_to_string(pid_file).ok()?.trim().parse().ok()
}

/// `kill(pid, 0)` — probes existence without signalling. `0` = alive, `EPERM` =
/// alive but not ours, `ESRCH` = gone. This is `DESIGN.md:205`'s rule; see the
/// note on [`SlotLock`] for why the mtime heuristic next door is not reused.
fn pid_alive(pid: i32) -> bool {
    if pid <= 0 {
        return false;
    }
    // SAFETY: `kill` with signal 0 sends nothing; it only reports whether the
    // pid exists. No memory is touched.
    unsafe {
        libc::kill(pid, 0) == 0 || io::Error::last_os_error().raw_os_error() == Some(libc::EPERM)
    }
}

// ── [compose] ────────────────────────────────────────────────────────────────

/// Expand `{prefix}` / `{slug}` then push the result through `sanitize_prefix`
/// before it can reach `docker -p` (§5). The placeholder set was validated as
/// CLOSED at parse time, so this is expansion, never interpretation.
pub fn compose_project_name(template: &str, prefix: &str, slug: &str) -> String {
    sanitize_prefix(&template.replace("{prefix}", prefix).replace("{slug}", slug))
}

/// The sanitized `COMPOSE_PROJECT_NAME` a place RECORDS, or `None`.
///
/// ⚠ §5 applies to this value exactly as it applies to the template. A
/// `.worktree.env` can be **committed** — `info/exclude` does nothing for a file
/// the clone already tracks — so what it says is repo-supplied text on its way to
/// a `docker -p` argv, and it goes through `sanitize_prefix` before it can get
/// there. A name that sanitizes to nothing is not a name.
pub fn recorded_compose_project(wt: &Path) -> Option<String> {
    read_env(wt).and_then(|(_, e)| e.compose_project).and_then(|n| sane_project(&n))
}

fn sane_project(name: &str) -> Option<String> {
    let s = sanitize_prefix(name);
    if s.is_empty() {
        None
    } else {
        Some(s)
    }
}

/// The project name for a place: what its `.worktree.env` says if it has one,
/// else the template. Reading the file first matters at teardown — the running
/// containers are named after whatever the stack was STARTED with, and the
/// template may have changed since.
pub fn compose_project_for(wt: &Path, compose: &Compose, prefix: &str, slug: &str) -> String {
    recorded_compose_project(wt)
        .unwrap_or_else(|| compose_project_name(&compose.project, prefix, slug))
}

/// `docker compose -f <file>… -p <project> down -v --remove-orphans`.
///
/// The argv is assembled HERE, from validated paths and a sanitized name — the
/// §5 line that must not be crossed is a command *string* coming from the repo,
/// and there is none. Output is captured rather than inherited so a teardown
/// cannot reformat the CLI's own output.
///
/// EVERY declared file is passed, in order: `down -v` removes only the volumes
/// declared in the files it is given, so dropping the base file leaks every
/// named volume the override does not repeat.
pub fn compose_down(files: &[PathBuf], project: &str) -> Result<(), String> {
    let mut cmd = Command::new("docker");
    cmd.arg("compose");
    for f in files {
        cmd.arg("-f").arg(f);
    }
    let out = cmd
        .arg("-p")
        .arg(project)
        .args(["down", "-v", "--remove-orphans"])
        .output()
        .map_err(|e| format!("docker not available ({e})"))?;
    if out.status.success() {
        return Ok(());
    }
    let err = String::from_utf8_lossy(&out.stderr);
    let first = err.lines().find(|l| !l.trim().is_empty()).unwrap_or("docker compose down failed");
    Err(first.trim().to_string())
}

// ── provision — the only filesystem write ────────────────────────────────────

/// One place to provision. A struct rather than eight positional arguments,
/// because `main_root`/`wt_root`/`wt` are three same-typed paths and swapping
/// two of them would be a silent disaster.
pub struct Request<'a> {
    pub main_root: &'a Path,
    pub wt_root: &'a Path,
    pub wt: &'a Path,
    pub prefix: &'a str,
    pub slug: &'a str,
    /// §6: the ONLY thing that may rewrite an existing `WORKTREE_SLOT`.
    pub reallocate: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Outcome {
    /// The project declares no `[ports]`; nothing is written at all.
    NoPorts,
    /// The slot was already held and the file is already byte-correct.
    Unchanged { slot: u32 },
    /// The slot was already held; the file was rewritten (the config's port map
    /// or compose name changed under it).
    Updated { slot: u32 },
    Allocated { slot: u32 },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProvisionError {
    Lock(String),
    /// Two places claiming one slot. `provision` REFUSES and never silently
    /// re-allocates: rewriting a slot under a running stack orphans containers
    /// on the old project name and moves ports the developer has bookmarked.
    Conflict { slot: u32, this: PathBuf, other: PathBuf },
    NoSlot(SlotError),
    Io(String),
}

impl fmt::Display for ProvisionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ProvisionError::Lock(m) | ProvisionError::Io(m) => write!(f, "{m}"),
            ProvisionError::NoSlot(e) => write!(f, "{e}"),
            ProvisionError::Conflict { slot, this, other } => write!(
                f,
                "slot {slot} is claimed by BOTH {} and {} — refusing to move a slot under a \
                 running stack",
                this.display(),
                other.display()
            ),
        }
    }
}

/// Allocate (or adopt) this place's slot and write `.worktree.env` (§6).
/// Idempotent: `new`, `relink` and `provision` all land on the same file.
pub fn provision(req: &Request, cfg: &ProjectConfig) -> Result<Outcome, ProvisionError> {
    let Some(ports) = cfg.ports.as_ref() else { return Ok(Outcome::NoPorts) };

    // `git worktree add` happened long before this; only the scan and the write
    // are inside the lock (§6).
    let _lock = SlotLock::acquire(req.main_root).map_err(ProvisionError::Lock)?;
    // This place's own file is read INSIDE the lock like the sibling scan is
    // (§6 step 3): the decision it feeds — "which slot does this place already
    // hold" — is the same decision the lock exists to serialize, and reading it
    // outside would mean deciding from a snapshot another provision may already
    // have moved.
    let existing = read_env(req.wt);
    let scan = scan(req.main_root, req.wt_root);

    // The compose name follows §6's slot rule, for the same reason: the RECORDED
    // name is what the running containers are named, so re-rendering it from a
    // template that changed since would leave `rm` downing a project nobody
    // started while the real stack keeps the ports. Only --reallocate moves it;
    // `doctor` reports the drift (Code::ComposeDrift).
    let compose = cfg.compose.as_ref().map(|c| {
        let recorded = if req.reallocate {
            None
        } else {
            existing.as_ref().and_then(|(_, e)| e.compose_project.as_deref()).and_then(sane_project)
        };
        recorded.unwrap_or_else(|| compose_project_name(&c.project, req.prefix, req.slug))
    });

    let slot = match existing.as_ref().and_then(|(_, e)| e.slot) {
        // §6 step 3 — already holds a slot. Adoption, not allocation: this is
        // what makes provision/relink/new idempotent, and what silently absorbs
        // the slots the bash script assigned before this tool existed (§12).
        Some(k) if !req.reallocate => {
            if let Some(other) = scan.other_claimant(k, req.wt) {
                return Err(ProvisionError::Conflict {
                    slot: k,
                    this: req.wt.to_path_buf(),
                    other: other.to_path_buf(),
                });
            }
            k
        }
        _ => select_slot(&scan.used_excluding(req.wt), ports.max_slots, |k| {
            slot_ports_free(ports, k)
        })
        .map_err(ProvisionError::NoSlot)?,
    };

    let text = render_env(slot, ports, compose.as_deref()).map_err(ProvisionError::Io)?;
    let held = existing.as_ref().map(|(_, e)| e.slot) == Some(Some(slot));
    if existing.as_ref().map(|(t, _)| t.as_str()) == Some(text.as_str()) {
        return Ok(Outcome::Unchanged { slot });
    }
    write_atomic(&req.wt.join(ENV_FILE), &text).map_err(|e| ProvisionError::Io(e.to_string()))?;
    Ok(if held { Outcome::Updated { slot } } else { Outcome::Allocated { slot } })
}

/// tmp in the SAME dir + `rename` — `store.rs:126-133`'s pattern, so a consumer
/// mid-`. .worktree.env` never sees a half-written file.
fn write_atomic(path: &Path, text: &str) -> io::Result<()> {
    let dir = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "no parent dir"))?;
    let tmp = dir.join(format!(".{ENV_FILE}.tmp-{}", std::process::id()));
    fs::write(&tmp, text)?;
    match fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = fs::remove_file(&tmp);
            Err(e)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::projcfg::{self, RelPath};

    fn ports(stride: u32, max_slots: u32, base: &[(&str, u32)]) -> Ports {
        Ports { stride, max_slots, base: base.iter().map(|(k, v)| (k.to_string(), *v)).collect() }
    }

    fn declared(v: &[u32]) -> BTreeSet<u32> {
        v.iter().copied().collect()
    }

    // ── slot selection, with no socket bound anywhere ────────────────────────

    #[test]
    fn the_lowest_free_slot_wins_and_holes_are_refilled() {
        // main is 0; 1 and 2 are taken → 3.
        assert_eq!(select_slot(&declared(&[0, 1, 2]), 50, |_| true), Ok(3));
        // a hole left by `rm` is reused immediately — there is no release step,
        // so the hole IS the release (§6).
        assert_eq!(select_slot(&declared(&[0, 1, 3, 4]), 50, |_| true), Ok(2));
        assert_eq!(select_slot(&declared(&[0]), 50, |_| true), Ok(1));
        // slot 0 is main's; nothing may be handed it even if it were free
        assert_eq!(select_slot(&declared(&[]), 50, |_| true), Ok(1));
    }

    #[test]
    fn a_conflicted_slot_counts_as_used_so_conflicts_never_compound() {
        // The scan collapses "1 is claimed twice" into "1 is claimed"; a third
        // place must skip it rather than become the third claimant.
        let scan = SlotScan {
            claims: BTreeMap::from([
                (0, vec![PathBuf::from("/repo")]),
                (1, vec![PathBuf::from("/repo/.worktrees/a"), PathBuf::from("/repo/.worktrees/b")]),
            ]),
        };
        let used = scan.used_excluding(Path::new("/repo/.worktrees/c"));
        assert_eq!(used, declared(&[0, 1]));
        assert_eq!(select_slot(&used, 50, |_| true), Ok(2));
        assert_eq!(scan.conflicts().len(), 1);
        // …and the place that legitimately holds 1 does not see itself as a
        // conflict with itself
        assert_eq!(scan.other_claimant(1, Path::new("/repo/.worktrees/a")).unwrap(), Path::new("/repo/.worktrees/b"));
        assert_eq!(scan.slot_of(Path::new("/repo/.worktrees/b")), Some(1));
        assert_eq!(scan.slot_of(Path::new("/repo/.worktrees/c")), None);
    }

    #[test]
    fn a_port_busy_slot_is_skipped_and_counted() {
        // 1 and 2 are declared; 3's ports are squatted by something unrelated.
        let free = |k: u32| k != 3;
        assert_eq!(select_slot(&declared(&[0, 1, 2]), 50, free), Ok(4));
    }

    #[test]
    fn exhaustion_names_how_many_are_declared_and_how_many_are_port_busy() {
        let e = select_slot(&declared(&[0, 1, 2]), 4, |k| k != 3 && k != 4).unwrap_err();
        assert_eq!(e, SlotError::Exhausted { max_slots: 4, declared: 2, busy: 2 });
        assert_eq!(
            e.to_string(),
            "no free slot in 1..=4 (2 declared by other places, 2 port-busy)"
        );
        // slot 0 is outside 1..=max_slots and is not counted as a declaration
        assert!(select_slot(&declared(&[0]), 1, |_| false).is_err());
    }

    // ── the wire format ──────────────────────────────────────────────────────

    #[test]
    fn the_emitted_env_file_is_byte_for_byte_what_consumers_source() {
        let p = ports(100, 50, &[("API", 3001), ("BACKOFFICE", 3000), ("PG", 5432)]);
        let s = render_env(3, &p, Some("cdv-wt-feat-x")).unwrap();
        assert_eq!(
            s,
            "# .worktree.env — generated by `worktrees provision`, one per worktree.\n\
             # Sourced as shell (`set -a; . .worktree.env`), so every line is KEY=value.\n\
             # WORKTREE_SLOT is yours: the tool never rewrites it without --reallocate.\n\
             WORKTREE_SLOT=3\n\
             COMPOSE_PROJECT_NAME=cdv-wt-feat-x\n\
             API_PORT=3301\n\
             BACKOFFICE_PORT=3300\n\
             PG_PORT=5732\n"
        );
        // no [compose] ⇒ no COMPOSE_PROJECT_NAME line at all (§3)
        let s = render_env(1, &p, None).unwrap();
        assert!(!s.contains("COMPOSE_PROJECT_NAME"), "{s}");
        // WORKTREE_SLOT is ALWAYS emitted — a consumer keys a behavior off its
        // mere presence, and dropping it reintroduces a debugged bug (§3).
        assert!(s.contains("\nWORKTREE_SLOT=1\n"), "{s}");
        // every emitted line is a shell assignment or a comment
        for l in s.lines() {
            assert!(l.starts_with('#') || l.split_once('=').is_some(), "not sourceable: {l}");
        }
    }

    #[test]
    fn a_base_key_that_is_not_shell_safe_is_refused_rather_than_emitted() {
        // Unreachable via projcfg::parse (lint_ports rejects it first) — but the
        // two are separated by a module boundary, and this line is the one that
        // decides whether .worktree.env ASSIGNS or EXECUTES.
        let bad = ports(100, 50, &[("PORT; rm -rf /", 3000)]);
        assert!(render_env(1, &bad, None).unwrap_err().contains("not a shell-safe name"));
        // and the guarantee it leans on really is enforced upstream
        assert!(projcfg::lint_ports(&bad).is_err());
        // same for a compose name that somehow skipped sanitize_prefix
        assert!(render_env(1, &ports(100, 50, &[("A", 3000)]), Some("a b;c"))
            .unwrap_err()
            .contains("not shell-safe"));
    }

    #[test]
    fn ports_are_base_plus_stride_times_k_and_stop_at_the_ceiling() {
        assert_eq!(port_for(3000, 100, 0).unwrap(), 3000);
        assert_eq!(port_for(3000, 100, 7).unwrap(), 3700);
        assert!(port_for(65000, 100, 10).is_err());
        let p = ports(100, 50, &[("API", 3001), ("PG", 5432)]);
        assert_eq!(
            slot_ports(&p, 2).unwrap(),
            vec![("API_PORT".to_string(), 3201), ("PG_PORT".to_string(), 5632)]
        );
    }

    #[test]
    fn an_existing_env_file_is_parsed_tolerantly_because_bash_wrote_it() {
        // §12: the migration is not a clean slate. This is the shape the cdv
        // script's file can have — export-prefixed, quoted, commented, CRLF.
        let text = "# worktree env\r\n\
                    export WORKTREE_SLOT=7\r\n\
                    export COMPOSE_PROJECT_NAME=\"cdv-wt-prod-reviews\"\r\n\
                    BACKOFFICE_PORT=3700   # the backoffice\r\n\
                    \r\n\
                    DATABASE_URL='postgres://x@localhost:5732/app'\r\n";
        let e = parse_env(text);
        assert_eq!(e.slot, Some(7));
        assert_eq!(e.compose_project.as_deref(), Some("cdv-wt-prod-reviews"));
        // the key set is what `doctor` checks a declared port against, so it
        // covers the same lenient shapes the values do
        assert!(e.keys.contains("WORKTREE_SLOT"), "{:?}", e.keys);
        assert!(e.keys.contains("BACKOFFICE_PORT"), "{:?}", e.keys);
        assert!(e.keys.contains("DATABASE_URL"), "{:?}", e.keys);
        assert!(!e.keys.contains("# worktree env"), "a comment is not a key: {:?}", e.keys);

        // our own output round-trips
        let ours = render_env(4, &ports(100, 50, &[("API", 3001)]), Some("p-wt-x")).unwrap();
        assert_eq!(
            parse_env(&ours),
            EnvFile {
                slot: Some(4),
                compose_project: Some("p-wt-x".into()),
                keys: ["WORKTREE_SLOT", "COMPOSE_PROJECT_NAME", "API_PORT"]
                    .iter()
                    .map(|s| s.to_string())
                    .collect(),
            }
        );

        // junk never panics and never invents a slot
        assert_eq!(parse_env("").slot, None);
        assert_eq!(parse_env("WORKTREE_SLOT=\nnot a line\n#WORKTREE_SLOT=9\n").slot, None);
        assert_eq!(parse_env("WORKTREE_SLOT=abc").slot, None);
        // last PARSEABLE assignment wins, like the shell
        assert_eq!(parse_env("WORKTREE_SLOT=1\nWORKTREE_SLOT=2\n").slot, Some(2));
        assert_eq!(parse_env("WORKTREE_SLOT=1\nWORKTREE_SLOT=oops\n").slot, Some(1));
        // an empty compose name is not a name
        assert_eq!(parse_env("COMPOSE_PROJECT_NAME=\n").compose_project, None);
        // `export` is a WORD — a tab after it is what an indented heredoc wrote
        assert_eq!(parse_env("export\tWORKTREE_SLOT=5\n").slot, Some(5));
        // …and a key that merely starts with those six letters is not an export
        assert_eq!(parse_env("exportWORKTREE_SLOT=5\n").slot, None);
        // a quoted value ends at its CLOSING quote: the quotes must not survive
        // into a name something later compares, or hands to `docker -p`
        assert_eq!(
            parse_env("COMPOSE_PROJECT_NAME=\"p-wt-x\"   # the stack\n").compose_project.as_deref(),
            Some("p-wt-x")
        );
        assert_eq!(parse_env("export\tWORKTREE_SLOT='6' # six\n").slot, Some(6));
    }

    // ── [compose] naming ─────────────────────────────────────────────────────

    #[test]
    fn the_compose_project_name_is_expanded_then_sanitized() {
        assert_eq!(compose_project_name("{prefix}-wt-{slug}", "cdv", "feat-x"), "cdv-wt-feat-x");
        // a slug with `/` or capitals cannot reach `docker -p` unsanitized
        assert_eq!(compose_project_name("{prefix}-wt-{slug}", "cdv", "Feat/X"), "cdv-wt-feat-x");
        assert_eq!(compose_project_name("static", "cdv", "x"), "static");
        // the sanitizer is what makes the value safe to emit UNQUOTED
        assert!(is_shell_word(&compose_project_name("{slug}", "p", "a b;rm -rf /")));
        // a name that sanitizes to nothing is not a name (belt for the parser's
        // own empty-value guard: `recorded` must never be Some(""))
        assert_eq!(sane_project(""), None);
        assert_eq!(sane_project("A B").as_deref(), Some("a-b"));
    }

    // ── the real thing, on a real (git-free) tmpdir ──────────────────────────

    /// Every fs test gets its OWN port window. These tests really do bind, and
    /// `cargo test` runs them in parallel — two tests probing one port make each
    /// other look busy, which is a flake, not a finding.
    static NEXT_BASE: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(34_001);

    struct Tmp(PathBuf, u32);
    impl Tmp {
        fn new(tag: &str) -> Tmp {
            let d = std::env::temp_dir().join(format!(
                "wtprov-{tag}-{}-{:?}",
                std::process::id(),
                std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
            ));
            fs::create_dir_all(d.join(".worktrees")).unwrap();
            Tmp(d, NEXT_BASE.fetch_add(1_000, std::sync::atomic::Ordering::Relaxed))
        }
        fn port(&self, off: u32, k: u32) -> u32 {
            self.1 + off + 100 * k
        }
        fn wt(&self, slug: &str) -> PathBuf {
            let p = self.0.join(".worktrees").join(slug);
            fs::create_dir_all(&p).unwrap();
            p
        }
        fn cfg(&self) -> ProjectConfig {
            ProjectConfig {
                files: Vec::new(),
                ports: Some(ports(100, 3, &[("API", self.1), ("PG", self.1 + 500)])),
                compose: Some(Compose {
                    files: vec![RelPath::parse("docker-compose.worktree.yml").unwrap()],
                    project: "{prefix}-wt-{slug}".into(),
                }),
                project: Default::default(),
            }
        }
        fn run_cfg(&self, slug: &str, reallocate: bool, cfg: &ProjectConfig) -> Result<Outcome, ProvisionError> {
            let wt = self.wt(slug);
            let wt_root = self.0.join(".worktrees");
            provision(
                &Request {
                    main_root: &self.0,
                    wt_root: &wt_root,
                    wt: &wt,
                    prefix: "proj",
                    slug,
                    reallocate,
                },
                cfg,
            )
        }
        fn run(&self, slug: &str, reallocate: bool) -> Result<Outcome, ProvisionError> {
            self.run_cfg(slug, reallocate, &self.cfg())
        }
    }
    impl Drop for Tmp {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn fs_provision_allocates_then_becomes_a_no_op() {
        let t = Tmp::new("idem");
        assert_eq!(t.run("a", false), Ok(Outcome::Allocated { slot: 1 }));
        let text = fs::read_to_string(t.wt("a").join(ENV_FILE)).unwrap();
        assert!(text.contains("WORKTREE_SLOT=1"), "{text}");
        assert!(text.contains("COMPOSE_PROJECT_NAME=proj-wt-a"), "{text}");
        assert!(text.contains(&format!("API_PORT={}", t.port(0, 1))), "{text}");

        // idempotent: same slot, and not one byte rewritten
        assert_eq!(t.run("a", false), Ok(Outcome::Unchanged { slot: 1 }));
        assert_eq!(fs::read_to_string(t.wt("a").join(ENV_FILE)).unwrap(), text);
        // a sibling takes the next slot, and the lock is released between runs
        assert_eq!(t.run("b", false), Ok(Outcome::Allocated { slot: 2 }));
        assert!(!t.0.join(LOCK_DIR).exists(), "the lock must not survive the call");
    }

    #[test]
    fn fs_a_hand_edited_slot_is_adopted_never_rewritten() {
        let t = Tmp::new("hand");
        let wt = t.wt("a");
        // whatever the old bash script wrote — a slot outside anything we would
        // have picked, in a format we did not emit
        fs::write(wt.join(ENV_FILE), "export WORKTREE_SLOT=3\n").unwrap();
        assert_eq!(t.run("a", false), Ok(Outcome::Updated { slot: 3 }));
        let text = fs::read_to_string(wt.join(ENV_FILE)).unwrap();
        assert!(text.contains("WORKTREE_SLOT=3"), "the user's slot survives: {text}");
        assert!(
            text.contains(&format!("API_PORT={}", t.port(0, 3))),
            "ports follow the adopted slot: {text}"
        );
        // and the next place does not collide with it
        assert_eq!(t.run("b", false), Ok(Outcome::Allocated { slot: 1 }));
    }

    #[test]
    fn fs_two_places_claiming_one_slot_is_refused_until_reallocate() {
        let t = Tmp::new("conflict");
        fs::write(t.wt("a").join(ENV_FILE), "WORKTREE_SLOT=2\n").unwrap();
        fs::write(t.wt("b").join(ENV_FILE), "WORKTREE_SLOT=2\n").unwrap();
        match t.run("a", false) {
            Err(ProvisionError::Conflict { slot, this, other }) => {
                assert_eq!(slot, 2);
                assert!(this.ends_with("a") && other.ends_with("b"), "{this:?} {other:?}");
            }
            other => panic!("expected a refusal, got {other:?}"),
        }
        // the file is untouched by the refusal
        assert_eq!(fs::read_to_string(t.wt("a").join(ENV_FILE)).unwrap(), "WORKTREE_SLOT=2\n");
        // --reallocate is the only way out, and it moves the one we ran on
        assert_eq!(t.run("a", true), Ok(Outcome::Allocated { slot: 1 }));
        assert_eq!(t.run("b", false), Ok(Outcome::Updated { slot: 2 }));
    }

    #[test]
    fn fs_exhaustion_is_an_error_that_names_the_shape_of_the_problem() {
        let t = Tmp::new("full"); // max_slots = 3
        for s in ["a", "b", "c"] {
            assert!(matches!(t.run(s, false), Ok(Outcome::Allocated { .. })));
        }
        match t.run("d", false) {
            Err(ProvisionError::NoSlot(e)) => {
                assert_eq!(e.to_string(), "no free slot in 1..=3 (3 declared by other places, 0 port-busy)")
            }
            other => panic!("expected exhaustion, got {other:?}"),
        }
        assert!(!t.wt("d").join(ENV_FILE).exists(), "nothing may be written on failure");
    }

    #[test]
    fn fs_a_project_with_no_ports_writes_nothing_at_all() {
        let t = Tmp::new("noports");
        assert_eq!(t.run_cfg("a", false, &ProjectConfig::default()), Ok(Outcome::NoPorts));
        assert!(!t.wt("a").join(ENV_FILE).exists());
        assert!(!t.0.join(LOCK_DIR).exists(), "and the lock is never even taken");
    }

    #[test]
    fn fs_a_hostile_recorded_compose_name_is_sanitized_before_it_can_reach_docker() {
        // §5: `.worktree.env` can be COMMITTED by the clone — `info/exclude` does
        // nothing for a file git already tracks — so what it records is
        // repo-supplied text on its way to a `docker -p` argv.
        let t = Tmp::new("cevil");
        let wt = t.wt("a");
        fs::write(
            wt.join(ENV_FILE),
            "WORKTREE_SLOT=1\nCOMPOSE_PROJECT_NAME=\"Evil Name; rm -rf /\" # hi\n",
        )
        .unwrap();
        let cfg = t.cfg();
        let compose = cfg.compose.as_ref().unwrap();
        let sane = "evil-name--rm--rf--";
        assert_eq!(compose_project_for(&wt, compose, "proj", "a"), sane);
        assert!(is_shell_word(&compose_project_for(&wt, compose, "proj", "a")));
        // …and the name provision then records is the sanitized one, so the two
        // paths cannot disagree about which containers `rm` tears down
        assert_eq!(t.run_cfg("a", false, &cfg), Ok(Outcome::Updated { slot: 1 }));
        let text = fs::read_to_string(wt.join(ENV_FILE)).unwrap();
        assert!(text.contains(&format!("COMPOSE_PROJECT_NAME={sane}\n")), "{text}");
        assert_eq!(compose_project_for(&wt, compose, "proj", "a"), sane);
    }

    #[test]
    fn fs_the_recorded_compose_name_survives_a_template_change_until_reallocate() {
        let t = Tmp::new("cname");
        assert_eq!(t.run("a", false), Ok(Outcome::Allocated { slot: 1 }));
        // Whatever is running now is named `proj-wt-a`. The template changes…
        let mut cfg = t.cfg();
        cfg.compose.as_mut().unwrap().project = "{prefix}-new-{slug}".into();
        // …and provision leaves the recorded name alone — not one byte rewritten,
        // exactly like a hand-edited WORKTREE_SLOT.
        assert_eq!(t.run_cfg("a", false, &cfg), Ok(Outcome::Unchanged { slot: 1 }));
        let text = fs::read_to_string(t.wt("a").join(ENV_FILE)).unwrap();
        assert!(text.contains("COMPOSE_PROJECT_NAME=proj-wt-a\n"), "{text}");
        // teardown therefore still finds the containers it started
        assert_eq!(
            compose_project_for(&t.wt("a"), cfg.compose.as_ref().unwrap(), "proj", "a"),
            "proj-wt-a"
        );
        // --reallocate is the only thing that moves it, same as the slot
        assert_eq!(t.run_cfg("a", true, &cfg), Ok(Outcome::Updated { slot: 1 }));
        let text = fs::read_to_string(t.wt("a").join(ENV_FILE)).unwrap();
        assert!(text.contains("COMPOSE_PROJECT_NAME=proj-new-a\n"), "{text}");
    }

    #[test]
    fn fs_a_lock_we_could_not_stamp_is_never_returned_as_held() {
        let t = Tmp::new("stamp");
        let me = std::process::id() as i32;
        // a write that cannot land (ENOENT, ENOSPC, …) is a LOST acquisition —
        // discarding that error would leave a legitimate holder looking pidless
        // and evicted 45ms later
        assert!(!stamp(&t.0.join("nope").join("pid"), me));
        // a write that "succeeds" but reads back as something else is
        // indistinguishable from being evicted inside the mkdir→write window
        assert!(!stamp(Path::new("/dev/null"), me));
        // and the stamp is the only door to Ok: a returned lock always carries a
        // pid we verified on disk
        let l = SlotLock::acquire(&t.0).unwrap();
        assert_eq!(read_pid(&t.0.join(LOCK_DIR).join("pid")), Some(me));
        drop(l);
    }

    #[test]
    fn fs_an_evicted_holder_does_not_release_the_new_holders_lock() {
        let t = Tmp::new("evict");
        let pid_file = t.0.join(LOCK_DIR).join("pid");
        let l = SlotLock::acquire(&t.0).unwrap();
        // Simulate the eviction: a waiter read the lock as pidless, removed it
        // and took it. The directory is now SOMEONE ELSE'S.
        fs::write(&pid_file, "999999\n").unwrap();
        drop(l);
        assert!(t.0.join(LOCK_DIR).exists(), "an evicted holder must not release someone else's lock");
        assert_eq!(read_pid(&pid_file), Some(999999), "and must not touch their stamp");
        // a holder that still owns its stamp releases normally
        fs::remove_file(&pid_file).unwrap();
        fs::remove_dir(t.0.join(LOCK_DIR)).unwrap();
        drop(SlotLock::acquire(&t.0).unwrap());
        assert!(!t.0.join(LOCK_DIR).exists());
    }

    #[test]
    fn fs_the_lock_is_reclaimed_from_a_dead_holder() {
        let t = Tmp::new("lock");
        // A pid that cannot be alive (pid 0 is never a user process here).
        fs::create_dir(t.0.join(LOCK_DIR)).unwrap();
        fs::write(t.0.join(LOCK_DIR).join("pid"), "0\n").unwrap();
        let l = SlotLock::acquire(&t.0).expect("a dead holder's lock is stale");
        assert_eq!(read_pid(&t.0.join(LOCK_DIR).join("pid")), Some(std::process::id() as i32));
        drop(l);
        assert!(!t.0.join(LOCK_DIR).exists());
        // our own pid IS alive, so a second acquire while one is held times out
        let _held = SlotLock::acquire(&t.0).unwrap();
        assert!(SlotLock::acquire(&t.0).is_err(), "a live holder must not be evicted");
    }
}
